# Default values for k8s-pub-path-routing-varnish.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
replicaCount: 2
image:
  repository: coco/k8s-pub-path-routing-varnish
  pullPolicy: IfNotPresent
